@extends(auth()->user()->role === 'workshop_manager' ? 'layouts.mobile' : 'layouts.admin')
@section('title',$workshop->name)
@section('page-title','Workshop Dashboard')
@push('styles')
<style>
.panel{background:#151b29;border:1px solid #262f47;border-radius:16px;padding:18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px}.stat b{font-size:26px;display:block}.ws-btn{border:0;border-radius:10px;padding:9px 13px;background:#3f6fe0;color:#fff;font-weight:700}.form-control,.form-select{background:#0f1625;border-color:#33405f;color:#fff}.modal-content{background:#151b29;color:#fff}.table{--bs-table-bg:transparent;--bs-table-color:#e8edf6;--bs-table-border-color:#29334a}.progress{height:9px;background:#26324c}
.cards-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.inv-card{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px;transition:border-color .2s,transform .2s,box-shadow .2s;cursor:pointer;display:block;text-decoration:none;color:inherit}
.inv-card:hover{border-color:#3f6fe0;transform:translateY(-3px);box-shadow:0 6px 24px rgba(63,111,224,.18);color:inherit;text-decoration:none}
.inv-card .inv-name{font-weight:700;font-size:15px;margin-bottom:6px;color:#e8edf6}
.inv-card .inv-meta{font-size:12px;color:#96a3bb;margin-bottom:10px}
.inv-card .inv-footer{display:flex;justify-content:space-between;align-items:center;margin-top:8px}
.inv-card .inv-loc{font-size:12px;color:#96a3bb}
.project-cards-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.project-card{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px;transition:border-color .2s,transform .2s,box-shadow .2s}
.project-card:hover{border-color:#3f6fe0;transform:translateY(-3px);box-shadow:0 6px 24px rgba(63,111,224,.18)}
@media(max-width:900px){.cards-grid{grid-template-columns:repeat(2,1fr)}.project-cards-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.page-content{padding:14px}}
@media(max-width:600px){body{overflow:auto}.panel{border-radius:20px;padding:15px;margin-bottom:14px}.stats{grid-template-columns:repeat(2,1fr);gap:9px}.stat{border-radius:16px;padding:13px}.stat b{font-size:22px}.desktop-head{display:none!important}.section-head{align-items:flex-start!important}.section-head .ws-btn{white-space:nowrap}.cards-grid{grid-template-columns:1fr}.project-cards-grid{grid-template-columns:1fr}.ws-btn{min-height:44px}.modal-dialog{margin:10px}.modal-content{border-radius:20px}.modal-footer .ws-btn{width:100%}}
</style>
@endpush
@section('content')
@if(auth()->user()->role === 'workshop_manager')
<div class="mobile-head"><div><div class="eyebrow">WORKSHOP MANAGER</div><h1>{{ $workshop->name }}</h1></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="icon-btn" title="Logout">↪</button></form></div>
<div class="hero-card"><div class="eyebrow">MAIN WORKSHOP</div><h2>{{ $workshop->name }}</h2><div class="muted">📍 {{ $workshop->location ?: 'Location not set' }}</div><div class="muted mt-1">In-charge: {{ $workshop->inCharge?->name ?: 'Not assigned' }}</div></div>
@endif
<div class="desktop-head d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><h2 class="mb-1">{{ $workshop->name }}</h2><div class="muted">{{ $workshop->location ?: 'Location not set' }} · In-charge: {{ $workshop->inCharge?->name ?: 'Not assigned' }}</div><div class="muted mt-1">{{ $workshop->description }}</div></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#editWorkshop">Edit Workshop Details</button></div>
@php $workers=$workshop->projects->where('status','!=','completed')->sum('worker_count'); $active=$workshop->projects->whereIn('status',['planned','in_progress','on_hold'])->count(); $low=$workshop->inventoryItems->filter(fn($i)=>(float)$i->quantity<=(float)$i->minimum_stock)->count(); @endphp
<div class="stats mb-4"><div class="stat"><b>{{ $workshop->inventoryItems->count() }}</b><span class="muted">Inventory Items</span></div><div class="stat"><b>{{ $workers }}</b><span class="muted">Workers</span></div><div class="stat"><b>{{ $active }}</b><span class="muted">Active Projects</span></div><div class="stat"><b>{{ $low }}</b><span class="muted">Low Stock</span></div></div>
<div class="panel mb-4" id="inventory"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Inventory</h4><small class="muted">Items available inside this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addItem">+ Add Item</button></div><div class="cards-grid">@forelse($workshop->inventoryItems as $item)<div class="inv-card" data-bs-toggle="modal" data-bs-target="#editItem{{ $item->id }}">@if($item->photo)<div class="mb-2"><img src="{{ Storage::url($item->photo) }}" style="width:100%;height:120px;object-fit:cover;border-radius:8px"></div>@endif<div class="inv-name">{{ $item->item_name }}</div><div class="inv-meta">{{ $item->category ?: 'Uncategorized' }} &nbsp;·&nbsp; Code: {{ $item->item_code ?: '—' }}</div>@if($item->purchased_from || $item->vendor_contact)<div class="inv-meta" style="color:#7eb3ff;font-size:11px">🛍 {{ $item->purchased_from ?: 'Vendor' }} &nbsp;·&nbsp; 📞 {{ $item->vendor_contact ?: 'No contact' }}</div>@endif<div class="inv-footer"><span class="badge bg-{{ (float)$item->quantity <= 0 ? 'danger' : ((float)$item->quantity <= (float)$item->minimum_stock ? 'warning' : 'success') }}">{{ $item->quantity+0 }} {{ $item->unit }}</span><span class="inv-loc">📍 {{ $item->location ?: 'No location' }}</span></div></div>@empty<p class="muted">No inventory items yet.</p>@endforelse</div></div>
<div class="panel" id="projects"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Projects</h4><small class="muted">Open a project to view complete details, photos and drawings</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addProject">+ Add Project</button></div><div class="project-cards-grid">@forelse($workshop->projects as $project)<a href="{{ route('workshops.projects.show',[$workshop,$project]) }}" class="text-decoration-none"><div class="project-card"><div class="d-flex justify-content-between align-items-start mb-2"><strong class="text-white" style="font-size:15px">{{ $project->title }}</strong><span class="badge" style="background:#1e2d4a;color:#7eb3ff;font-size:12px">{{ $project->progress }}%</span></div><div class="progress my-2"><div class="progress-bar" style="width:{{ $project->progress }}%;background:linear-gradient(90deg,#3f6fe0,#6ba3ff)"></div></div><div class="d-flex justify-content-between muted mt-2"><small>👷 {{ $project->worker_count }} workers · {{ str_replace('_',' ',ucfirst($project->status)) }}</small><small>📅 {{ $project->expected_completion_date?->format('d M Y') ?: 'No deadline' }}</small></div></div></a>@empty<p class="muted">No projects added.</p>@endforelse</div></div>
<div class="panel mt-4" id="tools"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Tools</h4><small class="muted">Tools available in this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addTool">+ Add Tool</button></div><div class="project-cards-grid">@forelse($workshop->tools as $tool)<div class="project-card" style="cursor:pointer" data-bs-toggle="modal" data-bs-target="#editTool{{ $tool->id }}">@if($tool->photo)<div class="mb-2"><img src="{{ Storage::url($tool->photo) }}" style="width:100%;height:120px;object-fit:cover;border-radius:8px"></div>@endif<div class="d-flex justify-content-between align-items-start mb-2"><strong class="text-white" style="font-size:15px">{{ $tool->tool_name }}</strong><span class="badge" style="background:#1e2d4a;color:#7eb3ff;font-size:12px">{{ $tool->condition ?: 'Unknown' }}</span></div><div class="d-flex justify-content-between muted mt-2"><small>⭐ {{ $tool->quality ?: 'N/A' }}</small><small>👤 {{ $tool->last_used_by ?: 'No record' }}</small></div></div>@empty<p class="muted">No tools added.</p>@endforelse</div></div>
@include('workshops.partials-modals')
@if(auth()->user()->role === 'workshop_manager')
<nav class="mobile-tabs"><a class="active" href="{{ route('workshops.index') }}"><b>🏭</b>Workshop</a><a href="#inventory"><b>📦</b>Inventory</a><a href="#projects"><b>🛠</b>Projects</a><a href="#tools"><b>🔧</b>Tools</a><a href="#" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;"><b>↑</b>Top</a></nav>
@endif
@endsection
