@extends(auth()->user()->role === 'workshop_manager' ? 'layouts.mobile' : 'layouts.admin')
@section('title',$workshop->name)
@section('page-title','Workshop Dashboard')
@push('styles')
<style>
.panel{background:#151b29;border:1px solid #262f47;border-radius:16px;padding:18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px}.stat b{font-size:26px;display:block}.ws-btn{border:0;border-radius:10px;padding:9px 13px;background:#3f6fe0;color:#fff;font-weight:700}.form-control,.form-select{background:#0f1625;border-color:#33405f;color:#fff}.modal-content{background:#151b29;color:#fff}.table{--bs-table-bg:transparent;--bs-table-color:#e8edf6;--bs-table-border-color:#29334a}.progress{height:9px;background:#26324c}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.page-content{padding:14px}.table-responsive{font-size:13px}}

@media(max-width:600px){body{overflow:auto}.panel{border-radius:20px;padding:15px;margin-bottom:14px}.stats{grid-template-columns:repeat(2,1fr);gap:9px}.stat{border-radius:16px;padding:13px}.stat b{font-size:22px}.desktop-head{display:none!important}.section-head{align-items:flex-start!important}.section-head .ws-btn{white-space:nowrap}.inventory-table thead{display:none}.inventory-table,.inventory-table tbody,.inventory-table tr,.inventory-table td{display:block;width:100%}.inventory-table tr{background:#101827;border:1px solid #28344d;border-radius:15px;padding:12px;margin-bottom:10px}.inventory-table td{border:0;padding:3px 0}.inventory-table td:before{content:attr(data-label);display:inline-block;min-width:88px;color:#96a3bb;font-size:11px}.inventory-table td:last-child{padding-top:9px}.inventory-table td:last-child:before{display:none}.inventory-table .btn{width:100%}.project-card{border-radius:16px;padding:14px}.ws-btn{min-height:44px}.modal-dialog{margin:10px}.modal-content{border-radius:20px}.modal-footer .ws-btn{width:100%}}
</style>
@endpush
@section('content')
@if(auth()->user()->role === 'workshop_manager')
<div class="mobile-head"><div><div class="eyebrow">WORKSHOP MANAGER</div><h1>{{ $workshop->name }}</h1></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="icon-btn" title="Logout">↪</button></form></div>
<div class="hero-card"><div class="eyebrow">MAIN WORKSHOP</div><h2>{{ $workshop->name }}</h2><div class="muted">📍 {{ $workshop->location ?: 'Location not set' }}</div><div class="muted mt-1">In-charge: {{ $workshop->inCharge?->name ?: 'Not assigned' }}</div></div>
@endif
<div class="desktop-head d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><h2 class="mb-1">{{ $workshop->name }}</h2><div class="muted">{{ $workshop->location ?: 'Location not set' }} · In-charge: {{ $workshop->inCharge?->name ?: 'Not assigned' }}</div><div class="muted mt-1">{{ $workshop->description }}</div></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#editWorkshop">Edit Workshop Details</button></div>
@php $workers=$workshop->projects->where('status','!=','completed')->sum('worker_count'); $active=$workshop->projects->whereIn('status',['planned','in_progress','on_hold'])->count(); $low=$workshop->inventoryItems->filter(fn($i)=>(float)$i->quantity<=(float)$i->minimum_stock)->count(); @endphp
<div class="stats mb-4"><div class="stat"><b>{{ $workshop->inventoryItems->count() }}</b><span class="muted">Inventory Items</span></div><div class="stat"><b>{{ $workers }}</b><span class="muted">Workers</span></div><div class="stat"><b>{{ $active }}</b><span class="muted">Active Projects</span></div><div class="stat"><b>{{ $low }}</b><span class="muted">Low Stock</span></div></div>
<div class="panel mb-4" id="inventory"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Inventory</h4><small class="muted">Items available inside this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addItem">+ Add Item</button></div><div class="table-responsive"><table class="table align-middle inventory-table"><thead><tr><th>Item</th><th>Code</th><th>Category</th><th>Stock</th><th>Location</th><th></th></tr></thead><tbody>@forelse($workshop->inventoryItems as $item)<tr><td data-label="Item"><strong>{{ $item->item_name }}</strong></td><td data-label="Code">{{ $item->item_code ?: '-' }}</td><td data-label="Category">{{ $item->category ?: '-' }}</td><td data-label="Stock"><span class="badge bg-{{ (float)$item->quantity <= 0 ? 'danger' : ((float)$item->quantity <= (float)$item->minimum_stock ? 'warning' : 'success') }}">{{ $item->quantity+0 }} {{ $item->unit }}</span></td><td data-label="Location">{{ $item->location ?: '-' }}</td><td><button class="btn btn-sm btn-outline-light" data-bs-toggle="modal" data-bs-target="#editItem{{ $item->id }}">Edit</button></td></tr>@empty<tr><td colspan="6" class="text-center muted">No inventory items</td></tr>@endforelse</tbody></table></div></div>
<div class="panel" id="projects"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Projects</h4><small class="muted">Open a project to view complete details, photos and drawings</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addProject">+ Add Project</button></div><div class="row g-3">@forelse($workshop->projects as $project)<div class="col-lg-6"><a href="{{ route('workshops.projects.show',[$workshop,$project]) }}" class="text-decoration-none text-white"><div class="stat project-card"><div class="d-flex justify-content-between"><strong>{{ $project->title }}</strong><span>{{ $project->progress }}%</span></div><div class="progress my-2"><div class="progress-bar" style="width:{{ $project->progress }}%"></div></div><div class="d-flex justify-content-between muted"><small>{{ $project->worker_count }} workers · {{ str_replace('_',' ',ucfirst($project->status)) }}</small><small>{{ $project->expected_completion_date?->format('d M Y') ?: 'No deadline' }}</small></div></div></a></div>@empty<div class="muted">No projects added.</div>@endforelse</div></div>
@include('workshops.partials-modals')
@if(auth()->user()->role === 'workshop_manager')
<nav class="mobile-tabs"><a class="active" href="{{ route('workshops.index') }}"><b>🏭</b>Workshop</a><a href="#inventory"><b>📦</b>Inventory</a><a href="#projects"><b>🛠</b>Projects</a><a href="#" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;"><b>↑</b>Top</a></nav>
@endif
@endsection
