
<?php $__env->startSection('title','Site Assets'); ?>
<?php $__env->startSection('page-title','Site Assets'); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2>Site Assets</h2><p class="muted mb-0">Manage machinery and equipment.</p></div><a class="btn btn-primary" href="<?php echo e(route('admin.site-assets.create')); ?>">Add Asset</a></div>
<form class="card card-body mb-4" method="GET"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="search" value="<?php echo e(request('search')); ?>" placeholder="Search assets"></div><div class="col-md-3"><select class="form-select" name="site_id"><option value="">All sites</option><?php $__currentLoopData = $sites; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $site): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($site->id); ?>" <?php if(request('site_id')==$site->id): echo 'selected'; endif; ?>><?php echo e($site->site_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><?php $__currentLoopData = ['available','working','maintenance','breakdown','inactive']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status); ?>" <?php if(request('status')===$status): echo 'selected'; endif; ?>><?php echo e(ucfirst($status)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-2"><button class="btn btn-outline-light w-100">Filter</button></div></div></form>
<div class="card overflow-hidden"><div class="table-responsive"><table class="table table-dark table-hover mb-0"><thead><tr><th>Code</th><th>Asset</th><th>Site</th><th>Category</th><th>Status</th><th></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $assets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $asset): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($asset->asset_code); ?></td><td><?php echo e($asset->asset_name); ?></td><td><?php echo e($asset->workSite->site_name ?? '-'); ?></td><td><?php echo e($asset->category); ?></td><td><?php echo e(ucfirst($asset->status)); ?></td><td class="text-end"><a class="btn btn-sm btn-primary" href="<?php echo e(route('admin.site-assets.edit',$asset)); ?>">Edit</a><form class="d-inline" method="POST" action="<?php echo e(route('admin.site-assets.destroy',$asset)); ?>" onsubmit="return confirm('Delete this asset?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-danger">Delete</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-4">No assets found.</td></tr><?php endif; ?></tbody></table></div></div><div class="mt-3"><?php echo e($assets->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Agelessone\resources\views\admin\site_assets\index.blade.php ENDPATH**/ ?>