<?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
<div class="row g-3">
<div class="col-md-6"><label class="form-label">Name *</label><input required class="form-control" name="name" value="<?php echo e(old('name',$user->name ?? '')); ?>"></div>
<div class="col-md-6"><label class="form-label">Email *</label><input required type="email" class="form-control" name="email" value="<?php echo e(old('email',$user->email ?? '')); ?>"></div>
<div class="col-md-4"><label class="form-label">Mobile</label><input class="form-control" name="mobile" value="<?php echo e(old('mobile',$user->mobile ?? '')); ?>"></div>
<div class="col-md-4"><label class="form-label">Role *</label><select required class="form-select" name="role"><option value="">Select role</option><?php $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('role',$user->role ?? '')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div class="col-md-4"><label class="form-label">Department</label><select class="form-select" name="department"><option value="">Select department</option><?php $__currentLoopData = $departments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $department): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($department); ?>" <?php if(old('department',$user->department ?? '')===$department): echo 'selected'; endif; ?>><?php echo e($department); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div class="col-md-4"><label class="form-label">Status *</label><select required class="form-select" name="status"><option value="active" <?php if(old('status',$user->status ?? 'active')==='active'): echo 'selected'; endif; ?>>Active</option><option value="inactive" <?php if(old('status',$user->status ?? '')==='inactive'): echo 'selected'; endif; ?>>Inactive</option></select></div>
<div class="col-md-4"><label class="form-label">Password <?php echo e(isset($user)?'(leave blank to keep)':'*'); ?></label><input <?php echo e(isset($user)?'':'required'); ?> type="password" class="form-control" name="password"></div>
<div class="col-md-4"><label class="form-label">Confirm Password</label><input type="password" class="form-control" name="password_confirmation"></div>
<div class="col-md-6"><label class="form-label">Photo</label><input type="file" class="form-control" name="photo" accept="image/*"></div>
<div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address"><?php echo e(old('address',$user->address ?? '')); ?></textarea></div>
<div class="col-12"><label class="form-label">Remarks</label><textarea class="form-control" name="remarks"><?php echo e(old('remarks',$user->remarks ?? '')); ?></textarea></div>
</div>
<?php /**PATH C:\xampp\htdocs\ageless-admin-panel\resources\views\admin\users\_form.blade.php ENDPATH**/ ?>