
<?php $__env->startSection('title',$workSite->site_name.' History'); ?>
<?php $__env->startSection('page-title','Work History'); ?>
<?php $__env->startSection('content'); ?>
<style>
.top-row{display:flex;justify-content:space-between;gap:15px;align-items:flex-start;margin-bottom:16px}.top-row h2{margin:0}.filter-box{background:#151b29;border:1px solid #262f47;border-radius:14px;padding:15px;margin-bottom:16px}.filter-grid{display:grid;grid-template-columns:1fr 1fr auto auto;gap:10px;align-items:end}.form-label{font-size:12px;color:#9aa7be}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.sum-card{background:#151b29;border:1px solid #262f47;border-radius:13px;padding:14px}.sum-card span{display:block;color:#8794ac;font-size:11px}.sum-card strong{font-size:23px}.table-wrap{background:#151b29;border:1px solid #262f47;border-radius:14px;overflow:auto}.table{margin:0;min-width:1100px}.table th{font-size:11px;color:#9ca9bf;text-transform:uppercase;padding:13px}.table td{font-size:12px;padding:13px;vertical-align:middle}.pill{padding:5px 8px;border-radius:999px;font-size:10px;font-weight:700}.done{background:#173f32;color:#89e3bc}.open{background:#5a4720;color:#ffdb80}@media(max-width:800px){.filter-grid{grid-template-columns:1fr 1fr}.summary{grid-template-columns:repeat(2,1fr)}}
</style>
<div class="top-row"><div><a href="<?php echo e(route('admin.work-history.index')); ?>" class="text-decoration-none">← All worksites</a><h2 class="mt-2"><?php echo e($workSite->site_name); ?></h2><div class="muted"><?php echo e($workSite->location ?: 'Location not added'); ?> · Default supervisor: <?php echo e($workSite->supervisor?->name ?? 'Not assigned'); ?></div></div></div>
<form class="filter-box" method="GET" action="<?php echo e(route('admin.work-history.show',$workSite)); ?>">
 <div class="filter-grid"><div><label class="form-label">From date</label><input class="form-control" type="date" name="from" value="<?php echo e($from); ?>" required></div><div><label class="form-label">To date</label><input class="form-control" type="date" name="to" value="<?php echo e($to); ?>" required></div><button class="btn btn-primary" type="submit">Check History</button><a class="btn btn-success" href="<?php echo e(route('admin.work-history.export',[$workSite,'from'=>$from,'to'=>$to])); ?>">⬇ Excel Download</a></div>
</form>
<div class="summary"><div class="sum-card"><span>Workers</span><strong><?php echo e($totalWorkers); ?></strong></div><div class="sum-card"><span>Total Work Hours</span><strong><?php echo e(number_format($totalMinutes/60,2)); ?></strong></div><div class="sum-card"><span>Completed Shifts</span><strong><?php echo e($completedShifts); ?></strong></div><div class="sum-card"><span>Open Shifts</span><strong><?php echo e($openShifts); ?></strong></div></div>
<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Worker</th><th>Trade</th><th>Zone</th><th>Supervisor</th><th>In</th><th>Out</th><th>Hours</th><th>Work</th><th>State</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $records; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($record->attendance_date?->format('d M Y')); ?></td><td><strong><?php echo e($record->worker?->name ?? 'Deleted worker'); ?></strong><br><span class="muted"><?php echo e($record->worker?->worker_code); ?></span></td><td><?php echo e($record->worker?->trade ?: '-'); ?></td><td><?php echo e($record->siteZone?->zone_name ?? 'General'); ?></td><td><?php echo e($record->supervisor?->name ?? $workSite->supervisor?->name ?? 'Not assigned'); ?></td><td><?php echo e($record->punch_in ?: '-'); ?></td><td><?php echo e($record->punch_out ?: '-'); ?></td><td><?php echo e(number_format(($record->working_minutes ?? 0)/60,2)); ?></td><td><?php echo e($record->work_description ?: '-'); ?></td><td><span class="pill <?php echo e($record->punch_out?'done':'open'); ?>"><?php echo e($record->punch_out?'Completed':'Inside'); ?></span></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="10" class="text-center p-4 muted">No workers found for this date range.</td></tr><?php endif; ?>
</tbody></table></div><div class="mt-3"><?php echo e($records->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Agelessone\resources\views\admin\work_history\show.blade.php ENDPATH**/ ?>