
<?php $__env->startSection('title',$workshop->name); ?>
<?php $__env->startSection('page-title','Workshop Dashboard'); ?>
<?php $__env->startPush('styles'); ?>
<style>
.panel{background:#151b29;border:1px solid #262f47;border-radius:16px;padding:18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px}.stat b{font-size:26px;display:block}.ws-btn{border:0;border-radius:10px;padding:9px 13px;background:#3f6fe0;color:#fff;font-weight:700}.form-control,.form-select{background:#0f1625;border-color:#33405f;color:#fff}.modal-content{background:#151b29;color:#fff}.table{--bs-table-bg:transparent;--bs-table-color:#e8edf6;--bs-table-border-color:#29334a}.progress{height:9px;background:#26324c}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.page-content{padding:14px}.table-responsive{font-size:13px}}

@media(max-width:600px){body{overflow:auto}.panel{border-radius:20px;padding:15px;margin-bottom:14px}.stats{grid-template-columns:repeat(2,1fr);gap:9px}.stat{border-radius:16px;padding:13px}.stat b{font-size:22px}.desktop-head{display:none!important}.section-head{align-items:flex-start!important}.section-head .ws-btn{white-space:nowrap}.inventory-table thead{display:none}.inventory-table,.inventory-table tbody,.inventory-table tr,.inventory-table td{display:block;width:100%}.inventory-table tr{background:#101827;border:1px solid #28344d;border-radius:15px;padding:12px;margin-bottom:10px}.inventory-table td{border:0;padding:3px 0}.inventory-table td:before{content:attr(data-label);display:inline-block;min-width:88px;color:#96a3bb;font-size:11px}.inventory-table td:last-child{padding-top:9px}.inventory-table td:last-child:before{display:none}.inventory-table .btn{width:100%}.project-card{border-radius:16px;padding:14px}.ws-btn{min-height:44px}.modal-dialog{margin:10px}.modal-content{border-radius:20px}.modal-footer .ws-btn{width:100%}}
</style>
<?php $__env->stopPush(); ?>
<?php $__env->startSection('content'); ?>
<?php if(auth()->user()->role === 'workshop_manager'): ?>
<div class="mobile-head"><div><div class="eyebrow">WORKSHOP MANAGER</div><h1><?php echo e($workshop->name); ?></h1></div><form method="POST" action="<?php echo e(route('logout')); ?>"><?php echo csrf_field(); ?><button class="icon-btn" title="Logout">↪</button></form></div>
<div class="hero-card"><div class="eyebrow">MAIN WORKSHOP</div><h2><?php echo e($workshop->name); ?></h2><div class="muted">📍 <?php echo e($workshop->location ?: 'Location not set'); ?></div><div class="muted mt-1">In-charge: <?php echo e($workshop->inCharge?->name ?: 'Not assigned'); ?></div></div>
<?php endif; ?>
<div class="desktop-head d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><h2 class="mb-1"><?php echo e($workshop->name); ?></h2><div class="muted"><?php echo e($workshop->location ?: 'Location not set'); ?> · In-charge: <?php echo e($workshop->inCharge?->name ?: 'Not assigned'); ?></div><div class="muted mt-1"><?php echo e($workshop->description); ?></div></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#editWorkshop">Edit Workshop Details</button></div>
<?php $workers=$workshop->projects->where('status','!=','completed')->sum('worker_count'); $active=$workshop->projects->whereIn('status',['planned','in_progress','on_hold'])->count(); $low=$workshop->inventoryItems->filter(fn($i)=>(float)$i->quantity<=(float)$i->minimum_stock)->count(); ?>
<div class="stats mb-4"><div class="stat"><b><?php echo e($workshop->inventoryItems->count()); ?></b><span class="muted">Inventory Items</span></div><div class="stat"><b><?php echo e($workers); ?></b><span class="muted">Workers</span></div><div class="stat"><b><?php echo e($active); ?></b><span class="muted">Active Projects</span></div><div class="stat"><b><?php echo e($low); ?></b><span class="muted">Low Stock</span></div></div>
<div class="panel mb-4" id="inventory"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Inventory</h4><small class="muted">Items available inside this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addItem">+ Add Item</button></div><div class="table-responsive"><table class="table align-middle inventory-table"><thead><tr><th>Item</th><th>Code</th><th>Category</th><th>Stock</th><th>Location</th><th></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $workshop->inventoryItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td data-label="Item"><strong><?php echo e($item->item_name); ?></strong></td><td data-label="Code"><?php echo e($item->item_code ?: '-'); ?></td><td data-label="Category"><?php echo e($item->category ?: '-'); ?></td><td data-label="Stock"><span class="badge bg-<?php echo e((float)$item->quantity <= 0 ? 'danger' : ((float)$item->quantity <= (float)$item->minimum_stock ? 'warning' : 'success')); ?>"><?php echo e($item->quantity+0); ?> <?php echo e($item->unit); ?></span></td><td data-label="Location"><?php echo e($item->location ?: '-'); ?></td><td><button class="btn btn-sm btn-outline-light" data-bs-toggle="modal" data-bs-target="#editItem<?php echo e($item->id); ?>">Edit</button></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center muted">No inventory items</td></tr><?php endif; ?></tbody></table></div></div>
<div class="panel" id="projects"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Projects</h4><small class="muted">Open a project to view complete details, photos and drawings</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addProject">+ Add Project</button></div><div class="row g-3"><?php $__empty_1 = true; $__currentLoopData = $workshop->projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="col-lg-6"><a href="<?php echo e(route('workshops.projects.show',[$workshop,$project])); ?>" class="text-decoration-none text-white"><div class="stat project-card"><div class="d-flex justify-content-between"><strong><?php echo e($project->title); ?></strong><span><?php echo e($project->progress); ?>%</span></div><div class="progress my-2"><div class="progress-bar" style="width:<?php echo e($project->progress); ?>%"></div></div><div class="d-flex justify-content-between muted"><small><?php echo e($project->worker_count); ?> workers · <?php echo e(str_replace('_',' ',ucfirst($project->status))); ?></small><small><?php echo e($project->expected_completion_date?->format('d M Y') ?: 'No deadline'); ?></small></div></div></a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="muted">No projects added.</div><?php endif; ?></div></div>
<?php echo $__env->make('workshops.partials-modals', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php if(auth()->user()->role === 'workshop_manager'): ?>
<nav class="mobile-tabs"><a class="active" href="<?php echo e(route('workshops.index')); ?>"><b>🏭</b>Workshop</a><a href="#inventory"><b>📦</b>Inventory</a><a href="#projects"><b>🛠</b>Projects</a><a href="#" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;"><b>↑</b>Top</a></nav>
<?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make(auth()->user()->role === 'workshop_manager' ? 'layouts.mobile' : 'layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Agelessone\resources\views/workshops/show.blade.php ENDPATH**/ ?>