<?php $__env->startSection('title','Security Activity'); ?>
<?php $__env->startSection('page-title','Security Activity'); ?>
<?php $__env->startSection('content'); ?>
<h4 class="mb-3">Visitor Entries</h4>
<div class="card card-dark p-3 mb-4"><div class="table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Photo</th><th>Name</th><th>Phone</th><th>Site</th><th>Security</th><th>Check In</th><th>Check Out</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $visitors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $visitor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><img src="<?php echo e(asset('storage/'.$visitor->photo)); ?>" width="56" height="56" style="object-fit:cover;border-radius:8px"></td><td><?php echo e($visitor->name); ?></td><td><?php echo e($visitor->mobile ?: '—'); ?></td><td><?php echo e($visitor->workSite?->site_name); ?></td><td><?php echo e($visitor->recordedBy?->name); ?></td><td><?php echo e($visitor->check_in_at?->format('d M Y h:i A')); ?></td><td><?php echo e($visitor->check_out_at?->format('d M Y h:i A') ?? '-'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center">No visitor records.</td></tr><?php endif; ?>
</tbody></table></div><?php echo e($visitors->links()); ?></div>

<h4 class="mb-3">Worker Attendance</h4>
<div class="card card-dark p-3"><div class="table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Worker</th><th>Site</th><th>Work</th><th>Supervisor</th><th>Date</th><th>Photos</th><th>Punch Time</th><th>Hours</th><th>Status</th><th>Security</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $workerAttendances; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($row->worker?->name); ?></strong><br><small><?php echo e($row->worker?->trade); ?></small></td><td><?php echo e($row->workSite?->site_name); ?></td><td><?php echo e($row->siteZone?->work_type ?? $row->work_description ?? '—'); ?><br><small><?php echo e($row->work_description); ?></small></td><td><?php echo e($row->supervisor?->name ?? '—'); ?></td><td><?php echo e($row->attendance_date?->format('d M Y')); ?></td><td><div class="d-flex gap-1"><?php if($row->punch_in_photo): ?><img src="<?php echo e(asset('storage/'.$row->punch_in_photo)); ?>" width="52" height="52" style="object-fit:cover;border-radius:8px"><?php endif; ?> <?php if($row->punch_out_photo): ?><img src="<?php echo e(asset('storage/'.$row->punch_out_photo)); ?>" width="52" height="52" style="object-fit:cover;border-radius:8px"><?php endif; ?></div></td><td><?php echo e($row->punch_in ?? '-'); ?><br><?php echo e($row->punch_out ?? '-'); ?></td><td><?php echo e(intdiv((int)$row->working_minutes,60)); ?>h <?php echo e(((int)$row->working_minutes)%60); ?>m</td><td><span class="badge bg-<?php echo e($row->status==='approved'?'success':($row->status==='rejected'?'danger':'warning')); ?>"><?php echo e(ucfirst($row->status)); ?></span></td><td><?php echo e($row->recordedBy?->name); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="10" class="text-center">No worker attendance records.</td></tr><?php endif; ?>
</tbody></table></div><?php echo e($workerAttendances->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ageless-admin-panel\resources\views\admin\security-activity.blade.php ENDPATH**/ ?>