
<?php $__env->startSection('title','Site Work'); ?>
<?php $__env->startSection('content'); ?>
<div style="display:flex;justify-content:space-between;gap:15px;align-items:flex-start;margin-bottom:16px"><div><h2 style="margin:0;color:#fff">Site Work / Zones</h2><p style="margin:5px 0 0;color:#8794ac">Manage work areas and progress across all sites.</p></div><a href="<?php echo e(route('admin.site-zones.create')); ?>" class="add-zone">+ Add Work</a></div>
<?php if(session('success')): ?><div class="success-note"><?php echo e(session('success')); ?></div><?php endif; ?>
<div class="zone-list"><?php $__empty_1 = true; $__currentLoopData = $zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="zone-row"><div><span class="site-name"><?php echo e($zone->site?->site_name ?? 'Unknown Site'); ?></span><h3><?php echo e($zone->zone_name); ?></h3><p><?php echo e($zone->work_type); ?> · <?php echo e(ucfirst(str_replace('_',' ',$zone->status))); ?> · <?php echo e($zone->progress); ?>%</p></div><div class="row-actions"><a href="<?php echo e(route('admin.work-sites.show',$zone->work_site_id)); ?>">View Site</a><a href="<?php echo e(route('admin.site-zones.edit',$zone)); ?>">Edit</a><form method="POST" action="<?php echo e(route('admin.site-zones.destroy',$zone)); ?>" onsubmit="return confirm('Delete this site work?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button>Delete</button></form></div></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-zone">No site work has been added.</div><?php endif; ?></div><div style="margin-top:16px"><?php echo e($zones->links()); ?></div>
<style>.add-zone,.row-actions a,.row-actions button{display:inline-flex;padding:9px 13px;border:0;border-radius:9px;background:#3f6fe0;color:#fff;text-decoration:none;font-size:12px;font-weight:800;cursor:pointer}.success-note{padding:11px 14px;margin-bottom:15px;background:#163425;color:#9ce8bf;border-radius:10px}.zone-list{display:grid;gap:12px}.zone-row{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:16px;border:1px solid #29344d;border-radius:13px;background:#151b29}.zone-row h3{margin:4px 0;color:#fff}.zone-row p,.site-name{margin:0;color:#8794ac;font-size:12px}.row-actions{display:flex;gap:8px;align-items:center}.row-actions form{margin:0}.row-actions button{background:#c44456}.empty-zone{padding:35px;text-align:center;background:#151b29;color:#8794ac;border-radius:13px}@media(max-width:700px){.zone-row{align-items:flex-start;flex-direction:column}.row-actions{width:100%;flex-wrap:wrap}.row-actions>*{flex:1;text-align:center;justify-content:center}}</style>
<?php $__env->stopSection(); ?>

<<<<<<<< HEAD:storage/framework/views/d40c6d719e21540ce335a3ee83dd383e.php
<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ageless-admin-panel\resources\views/admin/site_zones/index.blade.php ENDPATH**/ ?>
========
<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Agelessone\resources\views\admin\site_zones\index.blade.php ENDPATH**/ ?>
>>>>>>>> 2ed5218 (added added accept/reject,photo punching and user phno login):storage/framework/views/b30f840f993d5f7615411e1ebbd8064d.php
