
<?php $__env->startSection('title',$workshop->name); ?>
<?php $__env->startSection('page-title','Workshop Dashboard'); ?>
<?php $__env->startPush('styles'); ?>
<style>
.panel{background:#151b29;border:1px solid #262f47;border-radius:16px;padding:18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px}.stat b{font-size:26px;display:block}.ws-btn{border:0;border-radius:10px;padding:9px 13px;background:#3f6fe0;color:#fff;font-weight:700}.form-control,.form-select{background:#0f1625;border-color:#33405f;color:#fff}.modal-content{background:#151b29;color:#fff}.table{--bs-table-bg:transparent;--bs-table-color:#e8edf6;--bs-table-border-color:#29334a}.progress{height:9px;background:#26324c}
.cards-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.inv-card{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px;transition:border-color .2s,transform .2s,box-shadow .2s;cursor:pointer;display:block;text-decoration:none;color:inherit}
.inv-card:hover{border-color:#3f6fe0;transform:translateY(-3px);box-shadow:0 6px 24px rgba(63,111,224,.18);color:inherit;text-decoration:none}
.inv-card .inv-name{font-weight:700;font-size:15px;margin-bottom:6px;color:#e8edf6}
.inv-card .inv-meta{font-size:12px;color:#96a3bb;margin-bottom:10px}
.inv-card .inv-footer{display:flex;justify-content:space-between;align-items:center;margin-top:8px}
.inv-card .inv-loc{font-size:12px;color:#96a3bb}
.project-cards-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.project-card{background:#111827;border:1px solid #26324c;border-radius:14px;padding:16px;transition:border-color .2s,transform .2s,box-shadow .2s}
.project-card:hover{border-color:#3f6fe0;transform:translateY(-3px);box-shadow:0 6px 24px rgba(63,111,224,.18)}
@media(max-width:900px){.cards-grid{grid-template-columns:repeat(2,1fr)}.project-cards-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.page-content{padding:14px}}
@media(max-width:600px){body{overflow:auto}.panel{border-radius:20px;padding:15px;margin-bottom:14px}.stats{grid-template-columns:repeat(2,1fr);gap:9px}.stat{border-radius:16px;padding:13px}.stat b{font-size:22px}.desktop-head{display:none!important}.section-head{align-items:flex-start!important}.section-head .ws-btn{white-space:nowrap}.cards-grid{grid-template-columns:1fr}.project-cards-grid{grid-template-columns:1fr}.ws-btn{min-height:44px}.modal-dialog{margin:10px}.modal-content{border-radius:20px}.modal-footer .ws-btn{width:100%}}
</style>
<?php $__env->stopPush(); ?>
<?php $__env->startSection('content'); ?>
<?php if(auth()->user()->role === 'workshop_manager'): ?>
<div class="mobile-head"><div><div class="eyebrow">WORKSHOP MANAGER</div><h1><?php echo e($workshop->name); ?></h1></div><form method="POST" action="<?php echo e(route('logout')); ?>"><?php echo csrf_field(); ?><button class="icon-btn" title="Logout">↪</button></form></div>
<div class="hero-card"><div class="eyebrow">MAIN WORKSHOP</div><h2><?php echo e($workshop->name); ?></h2><div class="muted">📍 <?php echo e($workshop->location ?: 'Location not set'); ?></div><div class="muted mt-1">In-charge: <?php echo e($workshop->inCharge?->name ?: 'Not assigned'); ?></div></div>
<?php endif; ?>
<div class="desktop-head d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><h2 class="mb-1"><?php echo e($workshop->name); ?></h2><div class="muted"><?php echo e($workshop->location ?: 'Location not set'); ?> · In-charge: <?php echo e($workshop->inCharge?->name ?: 'Not assigned'); ?></div><div class="muted mt-1"><?php echo e($workshop->description); ?></div></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#editWorkshop">Edit Workshop Details</button></div>
<?php $workers=$workshop->projects->where('status','!=','completed')->sum('worker_count'); $active=$workshop->projects->whereIn('status',['planned','in_progress','on_hold'])->count(); $low=$workshop->inventoryItems->filter(fn($i)=>(float)$i->quantity<=(float)$i->minimum_stock)->count(); ?>
<div class="stats mb-4"><div class="stat"><b><?php echo e($workshop->inventoryItems->count()); ?></b><span class="muted">Inventory Items</span></div><div class="stat"><b><?php echo e($workers); ?></b><span class="muted">Workers</span></div><div class="stat"><b><?php echo e($active); ?></b><span class="muted">Active Projects</span></div><div class="stat"><b><?php echo e($low); ?></b><span class="muted">Low Stock</span></div></div>
<div class="panel mb-4" id="inventory"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Inventory</h4><small class="muted">Items available inside this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addItem">+ Add Item</button></div><div class="cards-grid"><?php $__empty_1 = true; $__currentLoopData = $workshop->inventoryItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="inv-card" data-bs-toggle="modal" data-bs-target="#editItem<?php echo e($item->id); ?>"><?php if($item->photo): ?><div class="mb-2"><img src="<?php echo e(Storage::url($item->photo)); ?>" style="width:100%;height:120px;object-fit:cover;border-radius:8px"></div><?php endif; ?><div class="inv-name"><?php echo e($item->item_name); ?></div><div class="inv-meta"><?php echo e($item->category ?: 'Uncategorized'); ?> &nbsp;·&nbsp; Code: <?php echo e($item->item_code ?: '—'); ?></div><?php if($item->purchased_from || $item->vendor_contact): ?><div class="inv-meta" style="color:#7eb3ff;font-size:11px">🛍 <?php echo e($item->purchased_from ?: 'Vendor'); ?> &nbsp;·&nbsp; 📞 <?php echo e($item->vendor_contact ?: 'No contact'); ?></div><?php endif; ?><div class="inv-footer"><span class="badge bg-<?php echo e((float)$item->quantity <= 0 ? 'danger' : ((float)$item->quantity <= (float)$item->minimum_stock ? 'warning' : 'success')); ?>"><?php echo e($item->quantity+0); ?> <?php echo e($item->unit); ?></span><span class="inv-loc">📍 <?php echo e($item->location ?: 'No location'); ?></span></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="muted">No inventory items yet.</p><?php endif; ?></div></div>
<div class="panel" id="projects"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Projects</h4><small class="muted">Open a project to view complete details, photos and drawings</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addProject">+ Add Project</button></div><div class="project-cards-grid"><?php $__empty_1 = true; $__currentLoopData = $workshop->projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('workshops.projects.show',[$workshop,$project])); ?>" class="text-decoration-none"><div class="project-card"><div class="d-flex justify-content-between align-items-start mb-2"><strong class="text-white" style="font-size:15px"><?php echo e($project->title); ?></strong><span class="badge" style="background:#1e2d4a;color:#7eb3ff;font-size:12px"><?php echo e($project->progress); ?>%</span></div><div class="progress my-2"><div class="progress-bar" style="width:<?php echo e($project->progress); ?>%;background:linear-gradient(90deg,#3f6fe0,#6ba3ff)"></div></div><div class="d-flex justify-content-between muted mt-2"><small>👷 <?php echo e($project->worker_count); ?> workers · <?php echo e(str_replace('_',' ',ucfirst($project->status))); ?></small><small>📅 <?php echo e($project->expected_completion_date?->format('d M Y') ?: 'No deadline'); ?></small></div></div></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="muted">No projects added.</p><?php endif; ?></div></div>
<div class="panel mt-4" id="tools"><div class="section-head d-flex justify-content-between mb-3"><div><h4 class="mb-1">Workshop Tools</h4><small class="muted">Tools available in this workshop</small></div><button class="ws-btn" data-bs-toggle="modal" data-bs-target="#addTool">+ Add Tool</button></div><div class="project-cards-grid"><?php $__empty_1 = true; $__currentLoopData = $workshop->tools; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tool): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="project-card" style="cursor:pointer" data-bs-toggle="modal" data-bs-target="#editTool<?php echo e($tool->id); ?>"><?php if($tool->photo): ?><div class="mb-2"><img src="<?php echo e(Storage::url($tool->photo)); ?>" style="width:100%;height:120px;object-fit:cover;border-radius:8px"></div><?php endif; ?><div class="d-flex justify-content-between align-items-start mb-2"><strong class="text-white" style="font-size:15px"><?php echo e($tool->tool_name); ?></strong><span class="badge" style="background:#1e2d4a;color:#7eb3ff;font-size:12px"><?php echo e($tool->condition ?: 'Unknown'); ?></span></div><div class="d-flex justify-content-between muted mt-2"><small>⭐ <?php echo e($tool->quality ?: 'N/A'); ?></small><small>👤 <?php echo e($tool->last_used_by ?: 'No record'); ?></small></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="muted">No tools added.</p><?php endif; ?></div></div>
<?php echo $__env->make('workshops.partials-modals', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php if(auth()->user()->role === 'workshop_manager'): ?>
<nav class="mobile-tabs"><a class="active" href="<?php echo e(route('workshops.index')); ?>"><b>🏭</b>Workshop</a><a href="#inventory"><b>📦</b>Inventory</a><a href="#projects"><b>🛠</b>Projects</a><a href="#tools"><b>🔧</b>Tools</a><a href="#" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;"><b>↑</b>Top</a></nav>
<?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make(auth()->user()->role === 'workshop_manager' ? 'layouts.mobile' : 'layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Agelessone\resources\views/workshops/show.blade.php ENDPATH**/ ?>