<?php $__env->startSection('content'); ?>
<style>body{background:#f4f7fb}.sup-wrap{max-width:1100px;margin:auto;padding:20px}.hero{background:linear-gradient(135deg,#2448a8,#5c42c9);color:white;border-radius:22px;padding:22px}.panel{background:white;border-radius:18px;padding:18px;margin-top:16px;box-shadow:0 8px 28px rgba(25,42,80,.08)}.stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:15px}.stat{background:#f3f6fc;border-radius:14px;padding:14px}.att-row{border-top:1px solid #e8edf5;padding:14px 0}.photo{width:56px;height:56px;border-radius:12px;object-fit:cover}.worker-card{border:1px solid #e1e8f2;border-radius:16px;padding:14px;margin-top:12px}.timeline{border-left:3px solid #dce5f4;padding-left:12px;margin:10px 0}.timeline-item{padding:5px 0}.worker-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}@media(max-width:700px){.stat-grid,.worker-grid{grid-template-columns:1fr}.sup-wrap{padding:12px}.table-responsive{font-size:13px}.hero{border-radius:16px}.panel{padding:14px}}</style>
<div class="sup-wrap">
<div class="hero d-flex justify-content-between align-items-start"><div><small>SITE SUPERVISOR</small><h2><?php echo e($site->site_name); ?></h2><div><?php echo e($site->location); ?></div></div><form method="POST" action="<?php echo e(route('logout')); ?>"><?php echo csrf_field(); ?><button class="btn btn-light btn-sm">Logout</button></form></div>
<?php if(session('success')): ?><div class="alert alert-success mt-3"><?php echo e(session('success')); ?></div><?php endif; ?> <?php if($errors->any()): ?><div class="alert alert-danger mt-3"><?php echo e($errors->first()); ?></div><?php endif; ?>
<div class="stat-grid"><div class="stat"><strong><?php echo e($site->zones->count()); ?></strong><div>Work Cases</div></div><div class="stat"><strong><?php echo e($pending->count()); ?></strong><div>Pending Approvals</div></div><div class="stat"><strong><?php echo e($today->where('status','approved')->count()); ?></strong><div>Approved Today</div></div></div>
<div class="panel"><h4>My Attendance</h4><?php if(!$attendance): ?><form method="POST" action="<?php echo e(route('attendance.punchin')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?><input type="hidden" name="location" value="<?php echo e($site->site_name); ?>"><input class="form-control mb-2" type="file" name="photo" accept="image/*" capture="user" required><button class="btn btn-success w-100">Photo + Punch In</button></form><?php elseif(!$attendance->punch_out): ?><form method="POST" action="<?php echo e(route('attendance.punchout')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?><input type="hidden" name="location" value="<?php echo e($site->site_name); ?>"><p>Punched in: <?php echo e($attendance->punch_in->format('h:i A')); ?></p><input class="form-control mb-2" type="file" name="photo" accept="image/*" capture="user" required><button class="btn btn-danger w-100">Photo + Punch Out</button></form><?php else: ?><div class="alert alert-success mb-0">Completed <?php echo e($attendance->punch_in->format('h:i A')); ?> - <?php echo e($attendance->punch_out->format('h:i A')); ?></div><?php endif; ?></div>
<div class="panel">
<h4>Add Worker</h4>
<form method="POST" action="<?php echo e(route('supervisor.workers.store')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?>
<div class="row g-2">
<div class="col-md-4"><input class="form-control" name="name" placeholder="Worker name" required></div>
<div class="col-md-3"><input class="form-control" name="mobile" placeholder="Mobile"></div>
<div class="col-md-3"><input class="form-control" name="trade" placeholder="Trade / skill" required></div>
<div class="col-md-2"><input class="form-control" type="file" name="photo" accept="image/*" capture="user" required></div>
</div><button class="btn btn-primary mt-2">Add Worker</button></form>
</div>
<div class="panel"><div class="d-flex justify-content-between align-items-center"><h4 class="mb-0">Workers Today</h4><span class="badge bg-primary"><?php echo e($site->workers->count()); ?> workers</span></div>
<div class="worker-grid mt-2">
<?php $__empty_1 = true; $__currentLoopData = $site->workers->where('active',true); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $worker): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<?php ($record = $today->get($worker->id)); ?>
<div class="worker-card">
<div class="d-flex gap-3 align-items-center"><?php if($worker->photo): ?><img class="photo" src="<?php echo e(asset('storage/'.$worker->photo)); ?>"><?php endif; ?><div><strong><?php echo e($worker->name); ?></strong><div class="text-muted small"><?php echo e($worker->worker_code); ?> · <?php echo e($worker->trade); ?></div></div></div>
<?php if(!$record): ?>
<form class="mt-3" method="POST" action="<?php echo e(route('supervisor.workers.start',$worker)); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?>
<select class="form-select mb-2" name="site_zone_id"><option value="">General / no work case</option><?php $__currentLoopData = $site->zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($zone->id); ?>"><?php echo e($zone->zone_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select>
<input class="form-control mb-2" name="work_name" placeholder="Starting work" required>
<input class="form-control mb-2" name="notes" placeholder="Notes (optional)">
<label class="small text-muted">Starting photo</label><input class="form-control mb-2" type="file" name="photo" accept="image/*" capture="environment" required>
<button class="btn btn-success w-100">Start Work</button></form>
<?php else: ?>
<div class="mt-2 small"><strong>Started:</strong> <?php echo e(date('h:i A',strtotime($record->punch_in))); ?> <?php if($record->punch_out): ?> · <strong>Ended:</strong> <?php echo e(date('h:i A',strtotime($record->punch_out))); ?> <?php endif; ?></div>
<div class="timeline"><?php $__currentLoopData = $record->workSessions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $session): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="timeline-item"><strong><?php echo e($session->work_name); ?></strong><div class="small text-muted"><?php echo e($session->started_at->format('h:i A')); ?> – <?php echo e($session->ended_at?->format('h:i A') ?? 'Now'); ?> · <?php echo e($session->minutes); ?> min <?php if($session->siteZone): ?> · <?php echo e($session->siteZone->zone_name); ?> <?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<?php if(!$record->punch_out): ?>
<details class="mb-2"><summary class="btn btn-outline-primary btn-sm w-100">Change Work</summary><form class="mt-2" method="POST" action="<?php echo e(route('supervisor.workers.change-work',$record)); ?>"><?php echo csrf_field(); ?><select class="form-select mb-2" name="site_zone_id"><option value="">General / no work case</option><?php $__currentLoopData = $site->zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($zone->id); ?>"><?php echo e($zone->zone_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><input class="form-control mb-2" name="work_name" placeholder="New work" required><input class="form-control mb-2" name="notes" placeholder="Reason / notes"><button class="btn btn-primary w-100">Move Worker</button></form></details>
<form method="POST" action="<?php echo e(route('supervisor.workers.end',$record)); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?><label class="small text-muted">Ending photo</label><input class="form-control mb-2" type="file" name="photo" accept="image/*" capture="environment" required><button class="btn btn-danger w-100">End Work</button></form>
<?php else: ?><div class="alert alert-success py-2 mb-0">Completed: <?php echo e(intdiv($record->working_minutes ?? 0,60)); ?>h <?php echo e(($record->working_minutes ?? 0)%60); ?>m</div><?php endif; ?>
<?php endif; ?>
</div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted">No workers added yet.</p><?php endif; ?>
</div></div>
<div class="panel"><h4>Add Work Case</h4><form method="POST" action="<?php echo e(route('supervisor.work-cases.store')); ?>"><?php echo csrf_field(); ?><div class="row g-2"><div class="col-md-4"><input class="form-control" name="zone_name" placeholder="Work case name" required></div><div class="col-md-4"><input class="form-control" name="work_type" placeholder="Work type" required></div><div class="col-md-4"><select class="form-select" name="supervisor_id"><option value="">Assign supervisor</option><?php $__currentLoopData = $assignableSupervisors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $person): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($person->id); ?>"><?php echo e($person->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-3"><select class="form-select" name="status"><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="on_hold">On Hold</option><option value="completed">Completed</option></select></div><div class="col-md-3"><input class="form-control" type="number" name="progress" value="0" min="0" max="100"></div><div class="col-md-3"><input class="form-control" type="date" name="start_date"></div><div class="col-md-3"><input class="form-control" type="date" name="expected_end_date"></div><div class="col-12"><textarea class="form-control" name="description" placeholder="Description"></textarea></div></div><button class="btn btn-primary mt-2">Add Work Case</button></form></div>
<div class="panel"><h4>Work Cases</h4><?php $__empty_1 = true; $__currentLoopData = $site->zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><form method="POST" action="<?php echo e(route('supervisor.work-cases.update',$zone)); ?>" class="att-row"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><div class="row g-2 align-items-center"><div class="col-md-3"><strong><?php echo e($zone->zone_name); ?></strong><div class="text-muted small"><?php echo e($zone->work_type); ?></div></div><div class="col-md-3"><select class="form-select" name="supervisor_id"><option value="">Unassigned</option><?php $__currentLoopData = $assignableSupervisors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $person): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($person->id); ?>" <?php if($zone->supervisor_id==$person->id): echo 'selected'; endif; ?>><?php echo e($person->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-2"><select class="form-select" name="status"><?php $__currentLoopData = ['not_started','in_progress','on_hold','completed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($s); ?>" <?php if($zone->status==$s): echo 'selected'; endif; ?>><?php echo e(ucfirst(str_replace('_',' ',$s))); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-2"><input class="form-control" type="number" name="progress" value="<?php echo e($zone->progress); ?>" min="0" max="100"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Update</button></div></div></form><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted">No work cases.</p><?php endif; ?></div>
<div class="panel"><h4>Pending Worker Attendance</h4><?php $__empty_1 = true; $__currentLoopData = $pending; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="att-row"><div class="d-flex gap-3 align-items-center"><?php if($record->punch_in_photo): ?><img class="photo" src="<?php echo e(asset('storage/'.$record->punch_in_photo)); ?>"><?php endif; ?><div class="flex-grow-1"><strong><?php echo e($record->worker->name); ?></strong><div class="text-muted small"><?php echo e($record->attendance_date->format('d M Y')); ?> · <?php echo e($record->punch_in); ?> - <?php echo e($record->punch_out ?: 'Inside'); ?> · Recorded by <?php echo e($record->recordedBy->name ?? '-'); ?></div></div></div><div class="d-flex gap-2 mt-2"><form method="POST" action="<?php echo e(route('supervisor.attendance.approve',$record)); ?>"><?php echo csrf_field(); ?><button class="btn btn-success btn-sm">Approve</button></form><form method="POST" action="<?php echo e(route('supervisor.attendance.reject',$record)); ?>" class="d-flex gap-2 flex-grow-1"><?php echo csrf_field(); ?><input class="form-control form-control-sm" name="rejection_reason" placeholder="Reason for rejection" required><button class="btn btn-danger btn-sm">Reject</button></form></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted">No pending attendance.</p><?php endif; ?></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ageless-admin-panel\resources\views\supervisor\dashboard.blade.php ENDPATH**/ ?>