<?php $__env->startSection('content'); ?>
<style>
body{background:#0e1320}.navbar{display:none!important}.security-app{max-width:720px;margin:auto;min-height:100vh;padding:18px 16px 90px;color:#edf2ff;background:linear-gradient(180deg,#11182a,#0e1320)}
.app-head,.row-between{display:flex;justify-content:space-between;align-items:center;gap:12px}.app-head{margin-bottom:16px}.app-head h2{margin:0;font-size:21px}.muted{color:#93a0b8;font-size:12px}.panel{background:#171f31;border:1px solid #28334b;border-radius:22px;padding:17px;margin-bottom:15px}.site-banner{background:linear-gradient(135deg,#4169e1,#8758e8)}.site-banner h3{margin:4px 0}.entry{border-top:1px solid #28334b;padding:14px 0}.entry:first-of-type{border-top:0}.badge-app{padding:5px 9px;border-radius:999px;font-size:11px}.pending{background:#594b21;color:#ffd971}.inside{background:#174c39;color:#79e6b9}.done{background:#1f3f70;color:#a9c8ff}.photo{width:44px;height:44px;object-fit:cover;border-radius:10px}.tabs{position:fixed;bottom:10px;left:50%;transform:translateX(-50%);width:min(688px,calc(100% - 24px));background:#171f31;border:1px solid #28334b;border-radius:20px;padding:11px;display:flex;justify-content:space-around}.tabs a{color:#dbe5f7;text-decoration:none;font-size:12px}.pagination{--bs-pagination-bg:#171f31;--bs-pagination-border-color:#36415a;--bs-pagination-color:#dbe5f7;--bs-pagination-hover-bg:#202a40}
</style>
<div class="security-app">
 <div class="app-head"><div><div class="muted">WORKPLACE HISTORY</div><h2><?php echo e($site->site_name); ?></h2></div><a class="btn btn-sm btn-outline-light" href="<?php echo e(route('security.dashboard')); ?>">Back</a></div>
 <div class="panel site-banner"><div class="muted" style="color:#e8e8ff">HISTORY FOR THIS SITE ONLY</div><h3><?php echo e($site->site_name); ?></h3><div><?php echo e($site->location ?: 'Location not added'); ?></div></div>
 <div class="panel"><h5>Worker History</h5>
 <?php $__empty_1 = true; $__currentLoopData = $workerAttendances; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
 <div class="entry"><div class="row-between"><div><strong><?php echo e($record->worker?->name ?? 'Deleted worker'); ?></strong><div class="muted"><?php echo e($record->attendance_date?->format('d M Y')); ?> · <?php echo e($record->worker?->worker_code); ?> · <?php echo e($record->siteZone?->zone_name ?? 'General work'); ?></div></div><span class="badge-app <?php echo e(!$record->punch_out?'inside':'done'); ?>"><?php echo e(!$record->punch_out?'Inside':ucfirst($record->status)); ?></span></div><div class="muted mt-2"><?php echo e($record->punch_in ?: '--'); ?> — <?php echo e($record->punch_out ?: 'Not punched out'); ?> · <?php echo e($record->work_description ?: 'No description'); ?></div></div>
 <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="muted mb-0">No worker attendance history for this workplace.</p><?php endif; ?>
 <div class="mt-3"><?php echo e($workerAttendances->links()); ?></div></div>
 <div class="panel"><h5>Visitor History</h5>
 <?php $__empty_1 = true; $__currentLoopData = $visitors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $visitor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
 <div class="entry"><div class="row-between"><div class="d-flex align-items-center gap-2"><img class="photo" src="<?php echo e(asset('storage/'.$visitor->photo)); ?>"><div><strong><?php echo e($visitor->name); ?></strong><div class="muted"><?php echo e($visitor->mobile); ?> · <?php echo e($visitor->check_in_at?->format('d M Y, h:i A')); ?></div></div></div><span class="badge-app <?php echo e($visitor->check_out_at?'done':'inside'); ?>"><?php echo e($visitor->check_out_at?'Checked out':'Inside'); ?></span></div><?php if($visitor->check_out_at): ?><div class="muted mt-2">Out: <?php echo e($visitor->check_out_at->format('d M Y, h:i A')); ?></div><?php endif; ?></div>
 <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="muted mb-0">No visitor history for this workplace.</p><?php endif; ?>
 <div class="mt-3"><?php echo e($visitors->links()); ?></div></div>
 <div class="tabs"><a href="<?php echo e(route('security.dashboard')); ?>">Home</a><a href="<?php echo e(route('security.dashboard')); ?>#add-worker">Add Worker</a><a href="<?php echo e(route('security.dashboard')); ?>#workers">Punch</a><a href="<?php echo e(route('security.history')); ?>">History</a></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ageless-admin-panel\resources\views\security\history.blade.php ENDPATH**/ ?>