@extends('layouts.admin')
@section('title', 'Inventory')
@section('page-title', 'Inventory Management')
@push('styles')
<style>
.inv-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.inv-actions{display:flex;gap:8px;flex-wrap:wrap}.inv-btn{border:0;border-radius:9px;padding:10px 14px;color:#fff;background:#3f6fe0;font-weight:700}.inv-btn.green{background:#159568}.inv-btn.orange{background:#c87816}.inv-btn.gray{background:#334155}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.summary-card{padding:18px;border:1px solid var(--line);border-radius:14px;background:var(--panel)}.summary-card span{color:var(--muted);font-size:12px}.summary-card strong{font-size:28px;display:block;margin-top:5px}.inventory-panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:18px}.filter-grid{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px}.table{color:var(--text);margin:0}.table>:not(caption)>*>*{background:transparent;color:inherit;border-color:var(--line);vertical-align:middle}.badge-stock{padding:6px 9px;border-radius:20px;font-size:11px;font-weight:800}.available{background:#153f33;color:#58d7a9}.low{background:#4b3514;color:#ffbe55}.out{background:#4b1e27;color:#ff8291}.history{max-height:410px;overflow:auto}.modal-content{background:#151b29;color:#e8edf6;border:1px solid #262f47}.modal-header,.modal-footer{border-color:#262f47}.form-control,.form-select{background:#0e1320;border-color:#334155;color:#fff}.form-control:focus,.form-select:focus{background:#0e1320;color:#fff}.form-select option{background:#0e1320}.tabs{display:flex;gap:8px;margin-bottom:15px}.tabs button{background:#1c2436;color:#a8b4cc;border:1px solid #334155;border-radius:9px;padding:9px 13px}.tabs button.active{background:#3f6fe0;color:#fff}.tab-pane-local{display:none}.tab-pane-local.active{display:block}@media(max-width:900px){.summary-grid{grid-template-columns:repeat(2,1fr)}.filter-grid{grid-template-columns:1fr}.inv-head{align-items:flex-start;flex-direction:column}}
</style>
@endpush
@section('content')
<div class="inv-head"><div><h2 class="mb-1">Inventory</h2><div class="muted">Office items, purchases, stock in/out, adjustments and complete movement history.</div></div><div class="inv-actions"><button class="inv-btn" data-bs-toggle="modal" data-bs-target="#addItem">+ Add Item</button><button class="inv-btn green" data-bs-toggle="modal" data-bs-target="#stockIn">Stock In</button><button class="inv-btn orange" data-bs-toggle="modal" data-bs-target="#stockOut">Stock Out</button><button class="inv-btn gray" data-bs-toggle="modal" data-bs-target="#adjust">Adjust</button></div></div>
@if($errors->any())<div class="alert alert-danger"><strong>Please correct these fields:</strong> {{ $errors->first() }}</div>@endif
<div class="summary-grid"><div class="summary-card"><span>Total Items</span><strong>{{ $summary['total_items'] }}</strong></div><div class="summary-card"><span>Available Stock</span><strong>{{ $summary['available_stock'] }}</strong></div><div class="summary-card"><span>Low Stock Items</span><strong>{{ $summary['low_stock'] }}</strong></div><div class="summary-card"><span>Out of Stock</span><strong>{{ $summary['out_of_stock'] }}</strong></div></div>
<div class="tabs"><button class="active" data-tab="items">Items & Stock</button><button data-tab="history">Movement History</button></div>
<div id="items" class="tab-pane-local active">
<div class="inventory-panel"><form method="GET"><div class="filter-grid"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search item, code, supplier or location"><select class="form-select" name="category_id"><option value="">All Categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select><select class="form-select" name="stock_status"><option value="">All Status</option><option value="available" @selected(request('stock_status')==='available')>Available</option><option value="low" @selected(request('stock_status')==='low')>Low Stock</option><option value="out" @selected(request('stock_status')==='out')>Out of Stock</option></select><button class="inv-btn">Filter</button></div></form></div>
<div class="inventory-panel table-responsive"><table class="table"><thead><tr><th>Item</th><th>Category</th><th>Location</th><th>Supplier</th><th>Stock</th><th>Purchase Price</th><th>Status</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->item_name }}</strong><div class="muted small">{{ $item->item_code }} @if($item->brand) · {{ $item->brand }} @endif</div></td><td>{{ $item->category->name ?? '-' }}</td><td>{{ $item->warehouse }}<div class="muted small">{{ $item->rack ?: 'No rack/shelf' }}</div></td><td>{{ $item->supplier ?: '-' }}</td><td><strong>{{ $item->stock }} {{ strtoupper($item->unit) }}</strong><div class="muted small">Minimum: {{ $item->minimum_stock }}</div></td><td>₹{{ number_format($item->purchase_price,2) }}</td><td>@if($item->stock<=0)<span class="badge-stock out">Out of Stock</span>@elseif($item->stock<=$item->minimum_stock)<span class="badge-stock low">Low Stock</span>@else<span class="badge-stock available">Available</span>@endif</td><td><button class="btn btn-sm btn-outline-light" data-bs-toggle="modal" data-bs-target="#edit{{ $item->id }}">Edit</button></td></tr>
<div class="modal fade" id="edit{{ $item->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form method="POST" action="{{ route('office-inventory.items.update',$item) }}" class="modal-content">@csrf @method('PUT')<div class="modal-header"><h5>Edit {{ $item->item_name }}</h5><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">@include('office_inventory.partials.item_fields',['editItem'=>$item])</div></div><div class="modal-footer"><button class="inv-btn">Update Item</button></div></form></div></div></div>
@empty<tr><td colspan="8" class="text-center py-5 muted">No office inventory items found.</td></tr>@endforelse</tbody></table><div class="mt-3">{{ $items->links() }}</div></div></div>
<div id="history" class="tab-pane-local"><div class="inventory-panel history table-responsive"><table class="table"><thead><tr><th>Date & Time</th><th>Item</th><th>Action</th><th>Qty</th><th>Stock Change</th><th>Person / Reference</th><th>Updated By</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at->format('d M Y, h:i A') }}</td><td>{{ $movement->item->item_name ?? '-' }}</td><td>{{ strtoupper(str_replace('_',' ',$movement->type)) }}</td><td>{{ $movement->quantity }}</td><td>{{ $movement->previous_stock }} → {{ $movement->new_stock }}</td><td>{{ $movement->issued_to ?: ($movement->reference_no ?: '-') }}<div class="muted small">{{ $movement->note }}</div></td><td>{{ $movement->user->name ?? 'System' }}</td></tr>@empty<tr><td colspan="7" class="text-center muted">No movement history yet.</td></tr>@endforelse</tbody></table></div></div>

@include('office_inventory.partials.action_modals')
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-pane-local').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}));</script>@endpush
